### ISSUE TITLE
Develop the Player Get, Delete and Update APIs

### ISSUE THREAD

**Issue by badrulme** [Royal-Club/royal-club-football#9]
Develop the Player Get, Delete and Update APIs

**Comment by akhter-rakib** [comment]
@badrulme bhai,
I have already incorporated the required APIs please check and let me know if you faces any issues.

**Comment by badrulme** [comment]
@akhter-rakib Bhai.
I did not get the Delete API.

**Comment by badrulme** [comment]
@akhter-rakib Bhai.
The retrieve API does not return the **employeeId** field.

**Comment by akhter-rakib** [comment]
I have incorporated @badrulme bhai
Please check it

**Comment by badrulme** [comment]
@akhter-rakib Bhai.
When I am calling the update API it sets the player status **InActive**.
![image](https://github.com/user-attachments/assets/156e0426-ed92-4018-a7de-98c55b03f372)
